[network]
name = \"simnet\"

[accounts.deployer]
mnemonic = \"abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon\"
balance = 100_000_000_000_000

[accounts.wallet_1]  
mnemonic = \"abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon\"
balance = 100_000_000_000_000

[accounts.wallet_2]
mnemonic = \"abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon\"
balance = 100_000_000_000_000

[accounts.wallet_3]
mnemonic = \"abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon\"
balance = 100_000_000_000_000

[accounts.wallet_4]
mnemonic = \"abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon\"
balance = 100_000_000_000_000
