[network]
name = "simnet"
rpc_url = "http://localhost:20443"

[accounts.deployer]
mnemonic = "sound idle panel often situate develop unit text design antenna vendor screen opinion balcony share trigger accuse scatter visa uniform brass update opinion media"
balance = 1000000000000